print("=" * 50)
print("> Main Menu")
print("=" * 50)
print("\t1. View all products")
print("\t2. Search for a product")
print("\t3. Add a new product")
print("\t4. Delete a product")
print("\t5. Checkout")
print("\t6. Exit")